name: "Build PR on main branch"
on:
  pull_request:
    branches: [ main ]
jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
      - name: "Check out repository code"
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
                  ${{ runner.os }}-gradle-

      - name: "Build Production release"
        run: ./gradlew app:assembleProdRelease

      - name: "Upload APK to Firebase App Distribution"
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_PROD_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: beta
          file: app/build/outputs/apk/prod/release/SolidApp.apk